# Generated by Django 5.1.3 on 2025-03-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maxiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('source_name', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
